### ISSUE TITLE
raw camera output

### ISSUE THREAD

**Issue by jmtatsch** [fpasteau/raspicam_node#3]
Hi,

would it be possible to get the raw uncompressed camera from your raspicam_node?
republishing as raw is taxing for the pi's cpu and moreover seems to be incompatible with ethzasl_ptam and rpg_svo :(

**Comment by fpasteau** [comment]
Hi,
I just wrote a quick (buggy) version of raspicam_node that outputs raw images in bgra8 format called raspicam_raw_node. Feel free to try it but it might not work properly as I haven't spend much time using it. I also don't know if it'll work correctly with ethzasl_ptam and rpg_svo.

**Comment by jmtatsch** [comment]
You are amazing! rpg_svo works now, although too slow to be usable :(
